#!/usr/bin/env python
__author__ = 'Marco Esposito'

import sys

from rqt_gui.main import Main

main = Main()
sys.exit(main.main(sys.argv, standalone='rqt_controller_manager.controller_manager_gui.ControllerManagerGUI'))